"""Constants for the Artifik External API — action types and timeline types."""

# -- Activity action constants ------------------------------------------------

ACTION_ASK_TO_QUALIFY = "ASK_TO_QUALIFY"
ACTION_AWARDING_PARTICIPANTS = "AWARDING_PARTICIPANTS"
ACTION_CONVERSATION_MARKED_COMPLETED = "CONVERSATION_MARKED_COMPLETED"
ACTION_DOFFIN_NOTICE_STATUS_PUBLISHED = "DOFFIN_NOTICE_STATUS_PUBLISHED"
ACTION_OPEN_BIDS = "OPEN_BIDS"
ACTION_OPEN_QUALIFICATIONS = "OPEN_QUALIFICATIONS"
ACTION_PUBLISH_TO_DOFFIN = "PUBLISH_TO_DOFFIN"
ACTION_QUALIFYING_PARTICIPANTS = "QUALIFYING_PARTICIPANTS"
ACTION_REJECT_PARTICIPATION = "REJECT_PARTICIPATION"
ACTION_SUBMIT_BID = "SUBMIT_BID"
ACTION_WITHDRAW_PARTICIPATION = "WITHDRAW_PARTICIPATION"

# -- Timeline type constants --------------------------------------------------

TIMELINE_SUBMISSION = "submission"
TIMELINE_AWARD_DECISION = "award decision"
