"""Constants for the Artifik External API — action types and timeline types."""

# -- Activity action constants ------------------------------------------------

ACTION_ASK_TO_QUALIFY = "ASK_TO_QUALIFY"
ACTION_AWARDING_PARTICIPANTS = "AWARDING_PARTICIPANTS"
ACTION_CONVERSATION_MARKED_COMPLETED = "CONVERSATION_MARKED_COMPLETED"
ACTION_CONVERSATION_REOPENED = "CONVERSATION_REOPENED"
ACTION_DOFFIN_NOTICE_STATUS_PUBLISHED = "DOFFIN_NOTICE_STATUS_PUBLISHED"
ACTION_OPEN_BIDS = "OPEN_BIDS"
ACTION_OPEN_QUALIFICATIONS = "OPEN_QUALIFICATIONS"
ACTION_PUBLISH_ADDITIONAL_INFORMATION = "PUBLISH_ADDITIONAL_INFORMATION"
ACTION_PUBLISH_CHANGE_PROCUREMENT = "PUBLISH_CHANGE_PROCUREMENT"
ACTION_PUBLISH_Q8A = "PUBLISH_Q8A"
ACTION_PUBLISH_TO_DOFFIN = "PUBLISH_TO_DOFFIN"
ACTION_QUALIFYING_PARTICIPANTS = "QUALIFYING_PARTICIPANTS"
ACTION_REJECT_PARTICIPATION = "REJECT_PARTICIPATION"
ACTION_SUBMIT_BID = "SUBMIT_BID"
ACTION_WITHDRAW_PARTICIPATION = "WITHDRAW_PARTICIPATION"

# -- Timeline type constants --------------------------------------------------

TIMELINE_SUBMISSION = "submission"
TIMELINE_AWARD_DECISION = "award decision"

# -- Action → display label mapping -------------------------------------------
# Used by the frontend hendelseslogg to show human-readable activity names.

ACTION_LABELS: dict[str, str] = {
    ACTION_ASK_TO_QUALIFY: "Forespørsel om deltakelse",
    ACTION_AWARDING_PARTICIPANTS: "Tildeling utført",
    ACTION_CONVERSATION_MARKED_COMPLETED: "Dialog fullført",
    ACTION_CONVERSATION_REOPENED: "Dialog gjenåpnet",
    ACTION_DOFFIN_NOTICE_STATUS_PUBLISHED: "Doffin-status publisert",
    ACTION_OPEN_BIDS: "Tilbudsåpning",
    ACTION_OPEN_QUALIFICATIONS: "Kvalifikasjoner åpnet",
    ACTION_PUBLISH_ADDITIONAL_INFORMATION: "Tilleggsinformasjon",
    ACTION_PUBLISH_CHANGE_PROCUREMENT: "Endring i konkurransen",
    ACTION_PUBLISH_Q8A: "Spørsmål og svar",
    ACTION_PUBLISH_TO_DOFFIN: "Publisert til Doffin",
    ACTION_QUALIFYING_PARTICIPANTS: "Kvalifiserte leverandører",
    ACTION_REJECT_PARTICIPATION: "Avvist",
    ACTION_SUBMIT_BID: "Tilbud mottatt",
    ACTION_WITHDRAW_PARTICIPATION: "Tilbaketrekking",
}
